=begin
#Aspose.Email for Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'date'

module SwaggerClient
  class HttpStatusCode
    
    100 = 100.freeze
    101 = 101.freeze
    200 = 200.freeze
    201 = 201.freeze
    202 = 202.freeze
    203 = 203.freeze
    204 = 204.freeze
    205 = 205.freeze
    206 = 206.freeze
    300 = 300.freeze
    300 = 300.freeze
    301 = 301.freeze
    301 = 301.freeze
    302 = 302.freeze
    302 = 302.freeze
    303 = 303.freeze
    303 = 303.freeze
    304 = 304.freeze
    305 = 305.freeze
    306 = 306.freeze
    307 = 307.freeze
    307 = 307.freeze
    400 = 400.freeze
    401 = 401.freeze
    402 = 402.freeze
    403 = 403.freeze
    404 = 404.freeze
    405 = 405.freeze
    406 = 406.freeze
    407 = 407.freeze
    408 = 408.freeze
    409 = 409.freeze
    410 = 410.freeze
    411 = 411.freeze
    412 = 412.freeze
    413 = 413.freeze
    414 = 414.freeze
    415 = 415.freeze
    416 = 416.freeze
    417 = 417.freeze
    426 = 426.freeze
    500 = 500.freeze
    501 = 501.freeze
    502 = 502.freeze
    503 = 503.freeze
    504 = 504.freeze
    505 = 505.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      consantValues = HttpStatusCode.constants.select{|c| c.to_s == value}
      raise "Invalid ENUM value #{value} for class #HttpStatusCode" if consantValues.empty?
      value
    end
  end

end
