=begin
#Aspose.Email for Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'date'

module SwaggerClient
  class SecurityOptions
    
    0 = 0.freeze
    1 = 1.freeze
    2 = 2.freeze
    256 = 256.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      consantValues = SecurityOptions.constants.select{|c| c.to_s == value}
      raise "Invalid ENUM value #{value} for class #SecurityOptions" if consantValues.empty?
      value
    end
  end

end
