=begin
#Aspose.Email for Cloud API Reference

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/email_document'
require 'swagger_client/models/email_properties'
require 'swagger_client/models/email_property'
require 'swagger_client/models/http_status_code'
require 'swagger_client/models/link'
require 'swagger_client/models/mail_server_folder'
require 'swagger_client/models/protocol_type'
require 'swagger_client/models/saa_spose_response'
require 'swagger_client/models/security_options'
require 'swagger_client/models/email_document_response'
require 'swagger_client/models/email_property_response'
require 'swagger_client/models/list_folders_response'
require 'swagger_client/models/list_response'
require 'swagger_client/models/mime_response'

# APIs
require 'swagger_client/api/email_api'
require 'swagger_client/api/email_client_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
